#!/usr/bin/env python
# -*- coding: utf-8 -*-

import typer
import numpy as np

from fcsorder.io.reader import StructureData
from fcsorder.genstr.tools import plot_distributions
from hiphive import ForceConstants
from hiphive.structure_generation import generate_phonon_rattled_structures


def phonon_rattle_cli(
    structure_file: str = typer.Argument(
        ..., help="Path to structure file (POSCAR, CIF, etc.)"
    ),
    force_constants_file: str = typer.Option(
        "FORCE_CONSTANTS",
        "--force-constants-file",
        "-fc",
        help="Path to FORCE_CONSTANTS file (Phonopy format)",
    ),
    num_structures: int = typer.Option(
        10,
        "--num-structures",
        "-n",
        help="Number of structures to generate per temperature",
        min=1,
    ),
    temperatures: list[float] = typer.Option(
        ...,
        "--temperature",
        "-T",
        help="Temperatures in Kelvin",
    ),
    use_qm_statistics: bool = typer.Option(
        False,
        "--use-qm-statistics/--no-qm-statistics",
        help="Use quantum-mechanical statistics for phonon amplitudes",
    ),
    imaginary_frequency_factor: float = typer.Option(
        1.0,
        "--imaginary-frequency-factor",
        help="Factor for treating imaginary frequencies",
        min=0.0,
    ),
    output_format: str = typer.Option(
        "vasp",
        "--output-format",
        "-f",
        help="Output format: vasp, cif, or xyz",
    ),
    output_prefix: str | None = typer.Option(
        None,
        "--output-prefix",
        "-p",
        help="Custom prefix for output filenames",
    ),
    apply_strain: bool = typer.Option(
        False,
        "--apply-strain/--no-strain",
        help="Apply random volumetric strain to structures",
    ),
    min_volume_ratio: float | None = typer.Option(
        0.9,
        "--min-volume-ratio",
        help="Minimum volume ratio for strain (when --apply-strain is enabled)",
    ),
    max_volume_ratio: float | None = typer.Option(
        1.05,
        "--max-volume-ratio",
        help="Maximum volume ratio for strain (when --apply-strain is enabled)",
    ),
):
    """Generate phonon-rattled structures for one or more temperatures.

    Structures are generated by superimposing harmonic phonon eigenmodes
    with random amplitudes consistent with the specified temperatures.
    The input structure is read from the structure file and force constants
    are read from the FORCE_CONSTANTS file (Phonopy format).
    """
    # Validate output format
    fmt = output_format.lower()
    if fmt not in {"vasp", "cif", "xyz"}:
        raise typer.BadParameter(
            f"Invalid format '{output_format}'. Must be one of: vasp, cif, xyz"
        )

    # Read structure
    structure_data = StructureData.from_file(structure_file)
    atoms = structure_data.to_atoms()
    
    # Read force constants
    # Determine format from file extension or default to 'text' for FORCE_CONSTANTS
    fc_format = None
    if force_constants_file.endswith('.hdf5'):
        fc_format = 'hdf5'
    else:
        fc_format = 'text'  # Default format for Phonopy FORCE_CONSTANTS
    
    fc = ForceConstants.read_phonopy(atoms, force_constants_file, format=fc_format)
    fc2_matrix = fc.get_fc_array(order=2, format='ase')
    reference_positions = atoms.get_positions().copy()

    # Validate volumetric strain options
    if apply_strain:
        if min_volume_ratio is None or max_volume_ratio is None:
            raise typer.BadParameter(
                "When --apply-strain is enabled, both --min-volume-ratio "
                "and --max-volume-ratio must be specified."
            )
        if min_volume_ratio <= 0 or max_volume_ratio <= 0:
            raise typer.BadParameter("Volume ratios must be positive.")
        if min_volume_ratio > max_volume_ratio:
            raise typer.BadParameter(
                "min_volume_ratio cannot be larger than max_volume_ratio."
            )

    # Calculate zero-padding width for indices
    total_structures = len(temperatures) * num_structures
    index_width = len(str(total_structures)) if total_structures > 0 else 1

    # Generate and write structures for each temperature
    for temperature in temperatures:
        structures = generate_phonon_rattled_structures(
            atoms=atoms,
            fc2=fc2_matrix,
            n_structures=num_structures,
            temperature=temperature,
            QM_statistics=use_qm_statistics,
            imag_freq_factor=imaginary_frequency_factor,
        )

        for i, structure in enumerate(structures):
            # Apply random volumetric strain if requested
            if apply_strain:
                volume_ratio = np.random.uniform(min_volume_ratio, max_volume_ratio)
                scale = volume_ratio ** (1.0 / 3.0)
                structure.set_cell(structure.get_cell() * scale, scale_atoms=True)

            # Generate output filename
            if output_prefix is not None:
                filename = f"{output_prefix}{i + 1:0{index_width}d}"
            else:
                filename = f"phonon_rattle_T{temperature:.1f}_{i + 1:0{index_width}d}"

            # Write structure
            structure_data_out = StructureData(atoms=structure)
            structure_data_out.to_file(filename, out_format=fmt)

        # Plot distributions for this temperature
        plot_distributions(structures, reference_positions, temperature)
